apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantsale-search
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/postgres:18.3
        name: db
        env:
          - name:  POSTGRES_PASSWORD
            value: password
        ports:
        - containerPort: 5432
          hostPort: 5432
  selector:
    matchLabels:
      app: plantsale-search
