// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FavoritesList struct {
	ID      int32
	PlantID string
	UserID  string
}

type Inatrualist struct {
	PlantID     string
	Summary     string
	ImageUrl    string
	Attribution string
	LastUpdated pgtype.Date
	FtsSummary  interface{}
}

type Plant struct {
	ID                 string
	Common             string
	Scientific         pgtype.Text
	InatrualistTaxonID pgtype.Text
	Section            pgtype.Text
	Color              pgtype.Text
	Bloom              pgtype.Text
	Height             pgtype.Text
	HeightSort         pgtype.Text
	Sun                pgtype.Text
	Water              pgtype.Text
	Price              pgtype.Numeric
	Available          bool
	FtsCommon          interface{}
	FtsScientific      interface{}
}

type PlantSearchView struct {
	ID                 string
	Common             string
	Scientific         pgtype.Text
	InatrualistTaxonID pgtype.Text
	Section            pgtype.Text
	Color              pgtype.Text
	Bloom              pgtype.Text
	Height             pgtype.Text
	HeightSort         pgtype.Text
	Sun                pgtype.Text
	Water              pgtype.Text
	Price              pgtype.Numeric
	Available          bool
	ImageUrl           pgtype.Text
	SearchVector       interface{}
}
