// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"
)

type Inatrualist struct {
	PlantID     string    `json:"plant_id"`
	Summary     string    `json:"summary"`
	ImageUrl    string    `json:"image_url"`
	Attribution string    `json:"attribution"`
	LastUpdated time.Time `json:"last_updated"`
}

type Plant struct {
	ID                 string         `json:"id"`
	Common             string         `json:"common"`
	Scientific         sql.NullString `json:"scientific"`
	InatrualistTaxonID sql.NullString `json:"inatrualist_taxon_id"`
	Section            sql.NullString `json:"section"`
	Color              sql.NullString `json:"color"`
	Bloom              sql.NullString `json:"bloom"`
	Height             sql.NullString `json:"height"`
	HeightSort         sql.NullString `json:"height_sort"`
	Sun                sql.NullString `json:"sun"`
	Water              sql.NullString `json:"water"`
	Price              string         `json:"price"`
	Available          bool           `json:"available"`
}
