// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
	"database/sql"
)

const createPlant = `-- name: CreatePlant :exec
INSERT INTO plants (
    id,
    common,
    scientific,
    inatrualist_taxon_id,
    section,
    color,
    bloom,
    height,
    height_sort,
    sun,
    water,
    price,
    available
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreatePlantParams struct {
	ID                 string         `json:"id"`
	Common             string         `json:"common"`
	Scientific         sql.NullString `json:"scientific"`
	InatrualistTaxonID sql.NullString `json:"inatrualist_taxon_id"`
	Section            sql.NullString `json:"section"`
	Color              sql.NullString `json:"color"`
	Bloom              sql.NullString `json:"bloom"`
	Height             sql.NullString `json:"height"`
	HeightSort         sql.NullString `json:"height_sort"`
	Sun                sql.NullString `json:"sun"`
	Water              sql.NullString `json:"water"`
	Price              string         `json:"price"`
	Available          bool           `json:"available"`
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) error {
	_, err := q.db.ExecContext(ctx, createPlant,
		arg.ID,
		arg.Common,
		arg.Scientific,
		arg.InatrualistTaxonID,
		arg.Section,
		arg.Color,
		arg.Bloom,
		arg.Height,
		arg.HeightSort,
		arg.Sun,
		arg.Water,
		arg.Price,
		arg.Available,
	)
	return err
}

const getAllPlants = `-- name: GetAllPlants :many
SELECT id, common, scientific, inatrualist_taxon_id, section, color, bloom, height, height_sort, sun, water, price, available FROM plants ORDER BY common
`

func (q *Queries) GetAllPlants(ctx context.Context) ([]Plant, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.Common,
			&i.Scientific,
			&i.InatrualistTaxonID,
			&i.Section,
			&i.Color,
			&i.Bloom,
			&i.Height,
			&i.HeightSort,
			&i.Sun,
			&i.Water,
			&i.Price,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlantsWithInatrualist = `-- name: GetAllPlantsWithInatrualist :many
SELECT
    p.id,
    p.common,
    p.scientific,
    p.inatrualist_taxon_id,
    p.section,
    p.color,
    p.bloom,
    p.height,
    p.height_sort,
    p.sun,
    p.water,
    p.price,
    p.available,
    i.summary,
    i.image_url,
    i.attribution
FROM plants p
LEFT JOIN inatrualist i ON i.plant_id = p.id
ORDER BY p.common
`

type GetAllPlantsWithInatrualistRow struct {
	ID                 string         `json:"id"`
	Common             string         `json:"common"`
	Scientific         sql.NullString `json:"scientific"`
	InatrualistTaxonID sql.NullString `json:"inatrualist_taxon_id"`
	Section            sql.NullString `json:"section"`
	Color              sql.NullString `json:"color"`
	Bloom              sql.NullString `json:"bloom"`
	Height             sql.NullString `json:"height"`
	HeightSort         sql.NullString `json:"height_sort"`
	Sun                sql.NullString `json:"sun"`
	Water              sql.NullString `json:"water"`
	Price              string         `json:"price"`
	Available          bool           `json:"available"`
	Summary            sql.NullString `json:"summary"`
	ImageUrl           sql.NullString `json:"image_url"`
	Attribution        sql.NullString `json:"attribution"`
}

func (q *Queries) GetAllPlantsWithInatrualist(ctx context.Context) ([]GetAllPlantsWithInatrualistRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlantsWithInatrualist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPlantsWithInatrualistRow
	for rows.Next() {
		var i GetAllPlantsWithInatrualistRow
		if err := rows.Scan(
			&i.ID,
			&i.Common,
			&i.Scientific,
			&i.InatrualistTaxonID,
			&i.Section,
			&i.Color,
			&i.Bloom,
			&i.Height,
			&i.HeightSort,
			&i.Sun,
			&i.Water,
			&i.Price,
			&i.Available,
			&i.Summary,
			&i.ImageUrl,
			&i.Attribution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSections = `-- name: GetDistinctSections :many
SELECT DISTINCT section FROM plants
WHERE section IS NOT NULL AND section != '' AND available = true
ORDER BY section
`

func (q *Queries) GetDistinctSections(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var section sql.NullString
		if err := rows.Scan(&section); err != nil {
			return nil, err
		}
		items = append(items, section)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSuns = `-- name: GetDistinctSuns :many
SELECT DISTINCT sun FROM plants
WHERE sun IS NOT NULL AND sun != '' AND available = true
ORDER BY sun
`

func (q *Queries) GetDistinctSuns(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctSuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var sun sql.NullString
		if err := rows.Scan(&sun); err != nil {
			return nil, err
		}
		items = append(items, sun)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctWaters = `-- name: GetDistinctWaters :many
SELECT DISTINCT water FROM plants
WHERE water IS NOT NULL AND water != '' AND available = true
ORDER BY water
`

func (q *Queries) GetDistinctWaters(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctWaters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var water sql.NullString
		if err := rows.Scan(&water); err != nil {
			return nil, err
		}
		items = append(items, water)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlantWithInatrualist = `-- name: GetPlantWithInatrualist :one
SELECT
    p.id,
    p.common,
    p.scientific,
    p.inatrualist_taxon_id,
    p.section,
    p.color,
    p.bloom,
    p.height,
    p.height_sort,
    p.sun,
    p.water,
    p.price,
    p.available,
    i.summary,
    i.image_url,
    i.attribution
FROM plants p
LEFT JOIN inatrualist i ON i.plant_id = p.id
WHERE p.id = ?
LIMIT 1
`

type GetPlantWithInatrualistRow struct {
	ID                 string         `json:"id"`
	Common             string         `json:"common"`
	Scientific         sql.NullString `json:"scientific"`
	InatrualistTaxonID sql.NullString `json:"inatrualist_taxon_id"`
	Section            sql.NullString `json:"section"`
	Color              sql.NullString `json:"color"`
	Bloom              sql.NullString `json:"bloom"`
	Height             sql.NullString `json:"height"`
	HeightSort         sql.NullString `json:"height_sort"`
	Sun                sql.NullString `json:"sun"`
	Water              sql.NullString `json:"water"`
	Price              string         `json:"price"`
	Available          bool           `json:"available"`
	Summary            sql.NullString `json:"summary"`
	ImageUrl           sql.NullString `json:"image_url"`
	Attribution        sql.NullString `json:"attribution"`
}

func (q *Queries) GetPlantWithInatrualist(ctx context.Context, id string) (GetPlantWithInatrualistRow, error) {
	row := q.db.QueryRowContext(ctx, getPlantWithInatrualist, id)
	var i GetPlantWithInatrualistRow
	err := row.Scan(
		&i.ID,
		&i.Common,
		&i.Scientific,
		&i.InatrualistTaxonID,
		&i.Section,
		&i.Color,
		&i.Bloom,
		&i.Height,
		&i.HeightSort,
		&i.Sun,
		&i.Water,
		&i.Price,
		&i.Available,
		&i.Summary,
		&i.ImageUrl,
		&i.Attribution,
	)
	return i, err
}

const searchPlants = `-- name: SearchPlants :many
SELECT
    p.id,
    p.common,
    p.scientific,
    p.inatrualist_taxon_id,
    p.section,
    p.color,
    p.bloom,
    p.height,
    p.height_sort,
    p.sun,
    p.water,
    p.price,
    p.available,
    i.image_url
FROM plants p
LEFT JOIN inatrualist i ON i.plant_id = p.id
WHERE p.available = true
  AND (
    ? = ''
    OR MATCH(p.common, p.scientific) AGAINST (? IN NATURAL LANGUAGE MODE)
    OR MATCH(i.summary) AGAINST (? IN NATURAL LANGUAGE MODE)
  )
  AND (? = '' OR p.section = ?)
  AND (?   = '' OR p.color   = ?)
  AND (?     = '' OR p.sun     = ?)
  AND (?   = '' OR p.water   = ?)
ORDER BY
    CASE ?
        WHEN 'common' THEN p.common
        WHEN 'height' THEN p.height_sort
        WHEN 'price' THEN p.price
        ELSE p.common
    END ASC,
    CASE WHEN ? = '' THEN 0 ELSE (
        (MATCH(p.common, p.scientific) AGAINST (? IN NATURAL LANGUAGE MODE))+
        (MATCH(i.summary) AGAINST (? IN NATURAL LANGUAGE MODE))
    ) END ASC,
    p.common ASC
`

type SearchPlantsParams struct {
	Query      string         `json:"query"`
	Query_2    string         `json:"query_2"`
	Query_3    string         `json:"query_3"`
	Section    sql.NullString `json:"section"`
	Color      sql.NullString `json:"color"`
	Sun        sql.NullString `json:"sun"`
	Water      sql.NullString `json:"water"`
	SortColumn interface{}    `json:"sort_column"`
	Query_5    string         `json:"query_5"`
	Query_6    string         `json:"query_6"`
}

type SearchPlantsRow struct {
	ID                 string         `json:"id"`
	Common             string         `json:"common"`
	Scientific         sql.NullString `json:"scientific"`
	InatrualistTaxonID sql.NullString `json:"inatrualist_taxon_id"`
	Section            sql.NullString `json:"section"`
	Color              sql.NullString `json:"color"`
	Bloom              sql.NullString `json:"bloom"`
	Height             sql.NullString `json:"height"`
	HeightSort         sql.NullString `json:"height_sort"`
	Sun                sql.NullString `json:"sun"`
	Water              sql.NullString `json:"water"`
	Price              string         `json:"price"`
	Available          bool           `json:"available"`
	ImageUrl           sql.NullString `json:"image_url"`
}

func (q *Queries) SearchPlants(ctx context.Context, arg SearchPlantsParams) ([]SearchPlantsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPlants,
		arg.Query,
		arg.Query_2,
		arg.Query_3,
		arg.Section,
		arg.Section,
		arg.Color,
		arg.Color,
		arg.Sun,
		arg.Sun,
		arg.Water,
		arg.Water,
		arg.SortColumn,
		arg.Query,
		arg.Query_5,
		arg.Query_6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPlantsRow
	for rows.Next() {
		var i SearchPlantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Common,
			&i.Scientific,
			&i.InatrualistTaxonID,
			&i.Section,
			&i.Color,
			&i.Bloom,
			&i.Height,
			&i.HeightSort,
			&i.Sun,
			&i.Water,
			&i.Price,
			&i.Available,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInatrualistData = `-- name: UpsertInatrualistData :exec
INSERT INTO inatrualist (
    plant_id,
    summary,
    image_url,
    attribution,
    last_updated
) VALUES (
    ?,
    ?,
    ?,
    ?,
    NOW()
) ON DUPLICATE KEY UPDATE
    summary      = VALUES(summary),
    image_url    = VALUES(image_url),
    attribution  = VALUES(attribution),
    last_updated = NOW()
`

type UpsertInatrualistDataParams struct {
	PlantID     string `json:"plant_id"`
	Summary     string `json:"summary"`
	ImageUrl    string `json:"image_url"`
	Attribution string `json:"attribution"`
}

func (q *Queries) UpsertInatrualistData(ctx context.Context, arg UpsertInatrualistDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertInatrualistData,
		arg.PlantID,
		arg.Summary,
		arg.ImageUrl,
		arg.Attribution,
	)
	return err
}
