// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlant = `-- name: CreatePlant :exec
INSERT INTO plants (
    id,
    common,
    scientific,
    inatrualist_taxon_id,
    section,
    color,
    bloom,
    height,
    height_sort,
    sun,
    water,
    price,
    available
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
`

type CreatePlantParams struct {
	ID                 string
	Common             string
	Scientific         pgtype.Text
	InatrualistTaxonID pgtype.Text
	Section            pgtype.Text
	Color              pgtype.Text
	Bloom              pgtype.Text
	Height             pgtype.Text
	HeightSort         pgtype.Text
	Sun                pgtype.Text
	Water              pgtype.Text
	Price              pgtype.Numeric
	Available          bool
}

func (q *Queries) CreatePlant(ctx context.Context, arg CreatePlantParams) error {
	_, err := q.db.Exec(ctx, createPlant,
		arg.ID,
		arg.Common,
		arg.Scientific,
		arg.InatrualistTaxonID,
		arg.Section,
		arg.Color,
		arg.Bloom,
		arg.Height,
		arg.HeightSort,
		arg.Sun,
		arg.Water,
		arg.Price,
		arg.Available,
	)
	return err
}

const getAllPlants = `-- name: GetAllPlants :many
SELECT id, common, scientific, inatrualist_taxon_id, section, color, bloom, height, height_sort, sun, water, price, available, fts_common FROM plants ORDER BY common
`

func (q *Queries) GetAllPlants(ctx context.Context) ([]Plant, error) {
	rows, err := q.db.Query(ctx, getAllPlants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.Common,
			&i.Scientific,
			&i.InatrualistTaxonID,
			&i.Section,
			&i.Color,
			&i.Bloom,
			&i.Height,
			&i.HeightSort,
			&i.Sun,
			&i.Water,
			&i.Price,
			&i.Available,
			&i.FtsCommon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlantsWithInatrualist = `-- name: GetAllPlantsWithInatrualist :many
SELECT
    p.id,
    p.common,
    p.scientific,
    p.inatrualist_taxon_id,
    p.section,
    p.color,
    p.bloom,
    p.height,
    p.height_sort,
    p.sun,
    p.water,
    p.price,
    p.available,
    i.summary,
    i.image_url,
    i.attribution
FROM plants p
LEFT JOIN inatrualist i ON i.plant_id = p.id
ORDER BY p.common
`

type GetAllPlantsWithInatrualistRow struct {
	ID                 string
	Common             string
	Scientific         pgtype.Text
	InatrualistTaxonID pgtype.Text
	Section            pgtype.Text
	Color              pgtype.Text
	Bloom              pgtype.Text
	Height             pgtype.Text
	HeightSort         pgtype.Text
	Sun                pgtype.Text
	Water              pgtype.Text
	Price              pgtype.Numeric
	Available          bool
	Summary            pgtype.Text
	ImageUrl           pgtype.Text
	Attribution        pgtype.Text
}

func (q *Queries) GetAllPlantsWithInatrualist(ctx context.Context) ([]GetAllPlantsWithInatrualistRow, error) {
	rows, err := q.db.Query(ctx, getAllPlantsWithInatrualist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPlantsWithInatrualistRow
	for rows.Next() {
		var i GetAllPlantsWithInatrualistRow
		if err := rows.Scan(
			&i.ID,
			&i.Common,
			&i.Scientific,
			&i.InatrualistTaxonID,
			&i.Section,
			&i.Color,
			&i.Bloom,
			&i.Height,
			&i.HeightSort,
			&i.Sun,
			&i.Water,
			&i.Price,
			&i.Available,
			&i.Summary,
			&i.ImageUrl,
			&i.Attribution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSections = `-- name: GetDistinctSections :many
SELECT DISTINCT section FROM plants
WHERE section IS NOT NULL AND section != '' AND available = true
ORDER BY section
`

func (q *Queries) GetDistinctSections(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getDistinctSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var section pgtype.Text
		if err := rows.Scan(&section); err != nil {
			return nil, err
		}
		items = append(items, section)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctSuns = `-- name: GetDistinctSuns :many
SELECT DISTINCT sun FROM plants
WHERE sun IS NOT NULL AND sun != '' AND available = true
ORDER BY sun
`

func (q *Queries) GetDistinctSuns(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getDistinctSuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var sun pgtype.Text
		if err := rows.Scan(&sun); err != nil {
			return nil, err
		}
		items = append(items, sun)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctWaters = `-- name: GetDistinctWaters :many
SELECT DISTINCT water FROM plants
WHERE water IS NOT NULL AND water != '' AND available = true
ORDER BY water
`

func (q *Queries) GetDistinctWaters(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getDistinctWaters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var water pgtype.Text
		if err := rows.Scan(&water); err != nil {
			return nil, err
		}
		items = append(items, water)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlantWithInatrualist = `-- name: GetPlantWithInatrualist :one
SELECT
    p.id,
    p.common,
    p.scientific,
    p.inatrualist_taxon_id,
    p.section,
    p.color,
    p.bloom,
    p.height,
    p.height_sort,
    p.sun,
    p.water,
    p.price,
    p.available,
    i.summary,
    i.image_url,
    i.attribution
FROM plants p
LEFT JOIN inatrualist i ON i.plant_id = p.id
WHERE p.id = $1
LIMIT 1
`

type GetPlantWithInatrualistRow struct {
	ID                 string
	Common             string
	Scientific         pgtype.Text
	InatrualistTaxonID pgtype.Text
	Section            pgtype.Text
	Color              pgtype.Text
	Bloom              pgtype.Text
	Height             pgtype.Text
	HeightSort         pgtype.Text
	Sun                pgtype.Text
	Water              pgtype.Text
	Price              pgtype.Numeric
	Available          bool
	Summary            pgtype.Text
	ImageUrl           pgtype.Text
	Attribution        pgtype.Text
}

func (q *Queries) GetPlantWithInatrualist(ctx context.Context, id string) (GetPlantWithInatrualistRow, error) {
	row := q.db.QueryRow(ctx, getPlantWithInatrualist, id)
	var i GetPlantWithInatrualistRow
	err := row.Scan(
		&i.ID,
		&i.Common,
		&i.Scientific,
		&i.InatrualistTaxonID,
		&i.Section,
		&i.Color,
		&i.Bloom,
		&i.Height,
		&i.HeightSort,
		&i.Sun,
		&i.Water,
		&i.Price,
		&i.Available,
		&i.Summary,
		&i.ImageUrl,
		&i.Attribution,
	)
	return i, err
}

const searchPlants = `-- name: SearchPlants :many
SELECT
    id,
    common,
    scientific,
    inatrualist_taxon_id,
    section,
    color,
    bloom,
    height,
    height_sort,
    sun,
    water,
    price,
    available,
    image_url
FROM plant_search_view
WHERE available = true
  AND (
    $1::text = ''
    OR search_vector @@ websearch_to_tsquery('english', $1::text)
  )
  AND ($2::text = '' OR section = $2::text)
  AND ($3::text   = '' OR color   = $3::text)
  AND ($4::text     = '' OR sun     = $4::text)
  AND ($5::text   = '' OR water   = $5::text)
ORDER BY
    CASE WHEN $1::text != '' THEN ts_rank(search_vector, websearch_to_tsquery('english', $1::text)) END DESC NULLS LAST,
    CASE WHEN $6::text = 'height' THEN height_sort END ASC NULLS LAST,
    CASE WHEN $6::text = 'price'  THEN price END ASC NULLS LAST,
    common ASC
`

type SearchPlantsParams struct {
	Query      string
	Section    string
	Color      string
	Sun        string
	Water      string
	SortColumn string
}

type SearchPlantsRow struct {
	ID                 string
	Common             string
	Scientific         pgtype.Text
	InatrualistTaxonID pgtype.Text
	Section            pgtype.Text
	Color              pgtype.Text
	Bloom              pgtype.Text
	Height             pgtype.Text
	HeightSort         pgtype.Text
	Sun                pgtype.Text
	Water              pgtype.Text
	Price              pgtype.Numeric
	Available          bool
	ImageUrl           pgtype.Text
}

func (q *Queries) SearchPlants(ctx context.Context, arg SearchPlantsParams) ([]SearchPlantsRow, error) {
	rows, err := q.db.Query(ctx, searchPlants,
		arg.Query,
		arg.Section,
		arg.Color,
		arg.Sun,
		arg.Water,
		arg.SortColumn,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPlantsRow
	for rows.Next() {
		var i SearchPlantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Common,
			&i.Scientific,
			&i.InatrualistTaxonID,
			&i.Section,
			&i.Color,
			&i.Bloom,
			&i.Height,
			&i.HeightSort,
			&i.Sun,
			&i.Water,
			&i.Price,
			&i.Available,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInatrualistData = `-- name: UpsertInatrualistData :exec
INSERT INTO inatrualist (
    plant_id,
    summary,
    image_url,
    attribution,
    last_updated
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW()
) ON CONFLICT (plant_id) DO UPDATE SET
    summary      = EXCLUDED.summary,
    image_url    = EXCLUDED.image_url,
    attribution  = EXCLUDED.attribution,
    last_updated = NOW()
`

type UpsertInatrualistDataParams struct {
	PlantID     string
	Summary     string
	ImageUrl    string
	Attribution string
}

func (q *Queries) UpsertInatrualistData(ctx context.Context, arg UpsertInatrualistDataParams) error {
	_, err := q.db.Exec(ctx, upsertInatrualistData,
		arg.PlantID,
		arg.Summary,
		arg.ImageUrl,
		arg.Attribution,
	)
	return err
}
